"""create initial schema 11 tables

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-11 05:24:20.206217+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("oid", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("default_card_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["default_card_id"],
            ["card.id"],
            name="fk_user_default_card_id",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_oid"), ["oid"], unique=True)

    op.create_table(
        "card",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("card_number_masked", sa.String(length=32), nullable=False),
        sa.Column("card_type", sa.String(length=8), nullable=False),
        sa.Column("card_provider", sa.String(length=64), nullable=False),
        sa.Column("nickname", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("card_type IN ('법인', '개인')", name="ck_card_type"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "card_number_masked", name="uq_card_user_number"),
    )
    with op.batch_alter_table("card", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_card_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ix_card_user_masked", ["user_id", "card_number_masked"], unique=False
        )

    op.create_table(
        "merchant",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("business_category", sa.String(length=128), nullable=True),
        sa.Column("auto_expense_column", sa.String(length=64), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("merchant", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_merchant_user_id"), ["user_id"], unique=False)

    op.create_table(
        "team_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("team_group", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_team_group_user_id"), ["user_id"], unique=False)

    op.create_table(
        "template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column("sheets_json", sa.JSON(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("template", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_template_user_id"), ["user_id"], unique=False)

    op.create_table(
        "vendor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_vendor_user_name"),
    )
    with op.batch_alter_table("vendor", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_vendor_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_vendor_user_last_used", ["user_id", "last_used_at"], unique=False)

    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("vendor_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendor.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vendor_id", "name", name="uq_project_vendor_name"),
    )
    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_project_user_id"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_project_vendor_id"), ["vendor_id"], unique=False)
        batch_op.create_index(
            "ix_project_vendor_last_used", ["vendor_id", "last_used_at"], unique=False
        )

    op.create_table(
        "team_member",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_group_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["team_group_id"], ["team_group.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("team_member", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_team_member_team_group_id"), ["team_group_id"], unique=False
        )

    op.create_table(
        "upload_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("year_month", sa.String(length=7), nullable=False),
        sa.Column("batch_card_type", sa.String(length=8), nullable=True),
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.Column("source_filenames", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.String(length=1024), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "batch_card_type IS NULL OR batch_card_type IN ('법인', '개인')",
            name="ck_upload_session_batch_card_type",
        ),
        sa.CheckConstraint(
            "status IN ('parsing', 'review', 'generated', 'failed')",
            name="ck_upload_session_status",
        ),
        sa.ForeignKeyConstraint(["template_id"], ["template.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("upload_session", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_upload_session_user_id"), ["user_id"], unique=False)

    op.create_table(
        "transaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("merchant_name", sa.String(length=255), nullable=False),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("transaction_time", sa.Time(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("supply_amount", sa.Integer(), nullable=True),
        sa.Column("vat", sa.Integer(), nullable=True),
        sa.Column("approval_number", sa.String(length=32), nullable=True),
        sa.Column("business_category", sa.String(length=128), nullable=True),
        sa.Column("card_number_masked", sa.String(length=32), nullable=True),
        sa.Column("card_provider", sa.String(length=64), nullable=False),
        sa.Column("card_type", sa.String(length=8), nullable=True),
        sa.Column("parser_used", sa.String(length=16), nullable=False),
        sa.Column("field_confidence", sa.JSON(), nullable=False),
        sa.Column("source_filename", sa.String(length=255), nullable=False),
        sa.Column("source_file_path", sa.String(length=512), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "card_type IS NULL OR card_type IN ('법인', '개인')", name="ck_transaction_card_type"
        ),
        sa.CheckConstraint(
            "parser_used IN ('rule_based', 'ocr_hybrid', 'llm')", name="ck_transaction_parser_used"
        ),
        sa.CheckConstraint("amount > 0", name="ck_transaction_amount_positive"),
        sa.ForeignKeyConstraint(["session_id"], ["upload_session.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_transaction_session_id"), ["session_id"], unique=False)
        batch_op.create_index(
            "ix_transaction_session_user", ["session_id", "user_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_transaction_user_id"), ["user_id"], unique=False)

    op.create_table(
        "expense_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("vendor_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("purpose", sa.String(length=255), nullable=True),
        sa.Column("attendees_json", sa.JSON(), nullable=False),
        sa.Column("headcount", sa.Integer(), nullable=True),
        sa.Column("receipt_attachment_path", sa.String(length=512), nullable=True),
        sa.Column("xlsx_sheet", sa.String(length=8), nullable=False),
        sa.Column("expense_column", sa.String(length=64), nullable=False),
        sa.Column("auto_note", sa.String(length=512), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("xlsx_sheet IN ('법인', '개인')", name="ck_expense_record_xlsx_sheet"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["transaction_id"], ["transaction.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendor.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transaction_id"),
    )
    with op.batch_alter_table("expense_record", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_expense_record_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_expense_record_vendor_id"), ["vendor_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expense_record", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_expense_record_vendor_id"))
        batch_op.drop_index(batch_op.f("ix_expense_record_user_id"))

    op.drop_table("expense_record")
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transaction_user_id"))
        batch_op.drop_index("ix_transaction_session_user")
        batch_op.drop_index(batch_op.f("ix_transaction_session_id"))

    op.drop_table("transaction")
    with op.batch_alter_table("upload_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_upload_session_user_id"))

    op.drop_table("upload_session")
    with op.batch_alter_table("team_member", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_team_member_team_group_id"))

    op.drop_table("team_member")
    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.drop_index("ix_project_vendor_last_used")
        batch_op.drop_index(batch_op.f("ix_project_vendor_id"))
        batch_op.drop_index(batch_op.f("ix_project_user_id"))

    op.drop_table("project")
    with op.batch_alter_table("vendor", schema=None) as batch_op:
        batch_op.drop_index("ix_vendor_user_last_used")
        batch_op.drop_index(batch_op.f("ix_vendor_user_id"))

    op.drop_table("vendor")
    with op.batch_alter_table("template", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_template_user_id"))

    op.drop_table("template")
    with op.batch_alter_table("team_group", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_team_group_user_id"))

    op.drop_table("team_group")
    with op.batch_alter_table("merchant", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_merchant_user_id"))

    op.drop_table("merchant")
    with op.batch_alter_table("card", schema=None) as batch_op:
        batch_op.drop_index("ix_card_user_masked")
        batch_op.drop_index(batch_op.f("ix_card_user_id"))

    op.drop_table("card")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_oid"))

    op.drop_table("user")
    # ### end Alembic commands ###
